export const VEHICLE_MAKES = [
  "Toyota",
  "Honda",
  "Nissan",
  "Hyundai",
  "Kia",
  "Mazda",
  "Mitsubishi",
  "Suzuki",
  "Chevrolet",
  "Ford",
  "Volkswagen",
  "BMW",
  "Mercedes-Benz",
  "Audi",
  "Jeep",
  "Isuzu",
  "Subaru",
  "Peugeot",
  "Renault",
  "BYD",
  "Chery",
  "Great Wall",
  "Otro",
] as const;

export const VEHICLE_MODELS: Record<string, readonly string[]> = {
  Toyota: ["Corolla", "Camry", "Yaris", "Hilux", "RAV4", "Fortuner", "Land Cruiser", "Prado", "Avanza", "Rush", "Tacoma", "4Runner", "Otro"],
  Honda: ["Civic", "Accord", "CR-V", "HR-V", "Fit", "City", "Pilot", "Odyssey", "Ridgeline", "Otro"],
  Nissan: ["Sentra", "Versa", "Altima", "Frontier", "X-Trail", "Kicks", "Pathfinder", "Navara", "March", "Otro"],
  Hyundai: ["Accent", "Elantra", "Tucson", "Santa Fe", "Creta", "i10", "i20", "Palisade", "Otro"],
  Kia: ["Rio", "Forte", "Sportage", "Sorento", "Seltos", "Picanto", "Soul", "Carnival", "Otro"],
  Mazda: ["Mazda2", "Mazda3", "CX-3", "CX-5", "CX-30", "CX-9", "BT-50", "Otro"],
  Mitsubishi: ["Lancer", "Outlander", "Montero", "ASX", "L200", "Xpander", "Otro"],
  Suzuki: ["Swift", "Vitara", "Jimny", "Ertiga", "Baleno", "S-Cross", "Alto", "Otro"],
  Chevrolet: ["Spark", "Aveo", "Cruze", "Tracker", "Traverse", "Silverado", "Colorado", "Tahoe", "Otro"],
  Ford: ["Fiesta", "Focus", "Escape", "Explorer", "Ranger", "F-150", "Bronco", "Edge", "Otro"],
  Volkswagen: ["Gol", "Jetta", "Polo", "Tiguan", "Amarok", "Virtus", "Taos", "Otro"],
  BMW: ["Serie 1", "Serie 3", "Serie 5", "X1", "X3", "X5", "Otro"],
  "Mercedes-Benz": ["Clase A", "Clase C", "Clase E", "GLA", "GLC", "GLE", "Otro"],
  Audi: ["A3", "A4", "A6", "Q3", "Q5", "Q7", "Otro"],
  Jeep: ["Renegade", "Compass", "Cherokee", "Wrangler", "Grand Cherokee", "Otro"],
  Isuzu: ["D-Max", "MU-X", "NPR", "Otro"],
  Subaru: ["Impreza", "Forester", "Outback", "XV", "Crosstrek", "Otro"],
  Peugeot: ["208", "301", "2008", "3008", "5008", "Partner", "Otro"],
  Renault: ["Logan", "Sandero", "Duster", "Kwid", "Captur", "Koleos", "Otro"],
  BYD: ["Song", "Yuan", "Han", "Tang", "Dolphin", "Seal", "Otro"],
  Chery: ["Tiggo 2", "Tiggo 3", "Tiggo 4", "Tiggo 7", "Tiggo 8", "Arrizo", "Otro"],
  "Great Wall": ["Poer", "Haval H6", "Haval Jolion", "Wingle", "Otro"],
  Otro: ["Otro"],
};

export function getModelsForMake(make: string): readonly string[] {
  return VEHICLE_MODELS[make] ?? ["Otro"];
}
